Repository AY2324S1-CS2103T-F12-1/tp, pull requests merged in 2023-10, with the labels that each got.

#50 Update user guide to contain v1.2 features
  docs/UserGuide.md
Labels: documentation

#51 Update glossary with noteworthy terms for developers.
  docs/DeveloperGuide.md
Labels: documentation

#54 Remove references from User Guide
  build.gradle
  docs/UserGuide.md
Labels: bug

#73 Branch add sort command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/SortByNameComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: enhancement

#70 Add an Appointment field for Person and a Schedule Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/NullAppointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#92 Fix bugs
  README.md
  src/main/java/seedu/address/ui/ClearWindow.java
Labels: bug

#91 Fixed bugs regarding Person equals() method and wrong error message r…
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: bug

#94 Bug fixes for Schedule Command. Add Testing for Appointment and Schedule command.
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: bug, enhancement

#118 Fix UI bug
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: bug

#123 Add prompt for updating appointment
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ConfirmOverrideCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OverrideWindow.java
  src/main/resources/view/OverrideWindow.fxml
  src/test/java/seedu/address/logic/commands/ConfirmOverrideCommandTest.java
Labels: enhancement

#125 Branch enhancement find more
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CombinedPredicateDiagram.puml
  docs/images/CombinedPredicate.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/GatherCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/predicates/CombinedPredicate.java
  src/main/java/seedu/address/model/person/predicates/FinancialPlanContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/CombinedPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/FinancialPlanContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicateTest.java
Labels: enhancement

#131 Branch bug combined predicate png
  docs/images/CombinedPredicate.png
Labels: bug

#137 Update implementation of ScheduleCommand in DG
  docs/DeveloperGuide.md
  docs/diagrams/ScheduleItemClassDiagram.puml
  docs/images/ScheduleItemClassDiagram.png
Labels: documentation
