Repository AY2324S1-CS2103T-F12-1/tp, pull requests merged in 2023-11, with the labels that each got.

#206 Update CompleteCommand to only accept either Index or LocalDate
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/logic/parser/CompleteCommandParser.java
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
Labels: bug, documentation

#209 Update Documentation for Schedule and Complete feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/CompleteActivityDiagram.puml
  docs/diagrams/CompleteSequenceDiagram.puml
  docs/diagrams/ScheduleActivityDiagram.puml
  docs/images/CompleteActivityDiagram.png
  docs/images/CompleteSequenceDiagram.png
  docs/images/ScheduleActivityDiagram.png
Labels: documentation

#212 Fix gather command bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/GatherCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug, documentation

#205 Fix some UG bugs
  docs/UserGuide.md
  docs/images/addUi.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/OverrideWindow.java
Labels: bug, documentation

#215 Branch bugs user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/completeUi.png
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/logic/commands/GatherCommand.java
Labels: bug, documentation

#216 Refactor Complete Command code
  src/main/java/seedu/address/logic/commands/CompleteByDate.java
  src/main/java/seedu/address/logic/commands/CompleteByIndex.java
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/logic/parser/CompleteCommandParser.java
  src/test/java/seedu/address/logic/commands/CompleteByDateTest.java
  src/test/java/seedu/address/logic/commands/CompleteByIndexTest.java
  src/test/java/seedu/address/logic/commands/CompleteCommandTest.java
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
Labels: enhancement

#222 UG and DG minor edits
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/GatherCommand.java
Labels: documentation

#228 Branch doc ppp
  docs/team/kb-tay.md
Labels: documentation

#229 Change Financial Plan and Tag message
  src/main/java/seedu/address/model/financialplan/FinancialPlan.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: bug

#230 Update PPP and minor changes
  docs/DeveloperGuide.md
  docs/team/kb-tay.md
  docs/team/sopa301.md
  src/main/java/seedu/address/logic/commands/GatherCommand.java
  src/main/java/seedu/address/logic/parser/GatherCommandParser.java
Labels: documentation

#240 Fix typos, improve readability and update Ui class diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#255 Update UG and improve SLAP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: documentation

#256 Fix invalid day bug
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug

#276 Fix bugs for gather command
  docs/UserGuide.md
  docs/images/gatherUi.png
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/GatherCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: bug, documentation

#281 Update UG and DG to remove references to non-wrapping tags and fps
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#289 Update the use cases
  docs/DeveloperGuide.md
Labels: documentation

#290 Update documentations for DG, UG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GatherClassDiagram.puml
  docs/diagrams/GatherSequenceDiagram.puml
  docs/diagrams/GatherSequenceDiagram1.puml
  docs/diagrams/GatherSequenceDiagram2.puml
  docs/images/GatherClassDiagram.png
  docs/images/GatherSequenceDiagram.png
  docs/images/GatherSequenceDiagram1.png
  docs/images/GatherSequenceDiagram2.png
  docs/team/alyssapng.md
  src/main/java/seedu/address/logic/commands/GatherCommand.java
  src/main/java/seedu/address/logic/parser/GatherCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/financialplan/FinancialPlan.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/gatheremail/GatherEmailByFinancialPlan.java
  src/main/java/seedu/address/model/person/gatheremail/GatherEmailByTag.java
  src/main/java/seedu/address/model/person/gatheremail/GatherEmailPrompt.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation

#288 Update PPP and add more manual testing instructions
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/sopa301.md
  src/main/resources/view/PersonListCard.fxml
Labels: documentation

#296 Add effort section
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: documentation

#298 Edit DG implementation
  docs/DeveloperGuide.md
  docs/team/alyssapng.md
  docs/team/nikele2001.md
  docs/team/sopa301.md
Labels: documentation

#301 Edit DG docs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation

#304 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#331 Fix formatting issues for PPP and DG
  docs/DeveloperGuide.md
  docs/images/CompleteSequenceDiagram.png
  docs/team/kb-tay.md
Labels: documentation

#332 Update PPP for Alyssa
  docs/team/alyssapng.md
Labels: documentation

#333 Update UG and PPP
  docs/UserGuide.md
  docs/team/alyssapng.md
Labels: documentation

#334 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nikele2001.md
Labels: documentation

#342 Update UG
  docs/UserGuide.md
Labels: documentation

#343 Update UG
  README.md
  docs/UserGuide.md
Labels: documentation
